-- FlowPilot — all migrations, in order.
--
-- Generated by scripts/build-combined-migration.mjs. Do not edit directly;
-- edit the files in supabase/migrations and regenerate.
--
-- Paste the whole file into the Supabase SQL Editor and run it once.
-- Intended for a fresh project — it is not written to be re-run.

-- ======================================================================
-- 20260731120000_initial_schema.sql
-- ======================================================================

-- FlowPilot initial schema
--
-- Multi-tenant from the first table. Every tenant-scoped table carries
-- business_id and ships with a row-level security policy in this same
-- migration — see docs/DECISIONS.md D3. Retrofitting RLS later is a migration
-- with a data-exposure window, and there is no reason to accept that when it is
-- free now.
--
-- Status and role columns use text + CHECK rather than Postgres enums.
-- Enums require an ALTER TYPE to extend and cannot drop values at all, which
-- makes every future plan tier or lead state a schema migration. The CHECK
-- constraint gives the same integrity with a far cheaper change path.

-- ---------------------------------------------------------------------------
-- Tenancy
-- ---------------------------------------------------------------------------

create table public.business (
  id uuid primary key default gen_random_uuid(),

  name text not null,

  -- Marketing and reporting only. Nothing in the application may branch on
  -- this — see docs/BUSINESS-PROFILE.md. A plumber and a cleaner differ in
  -- their configured data, never in a code path keyed off this column.
  industry_label text,

  -- Places served. Used to flag out-of-area jobs, never to refuse a caller.
  service_area text[] not null default '{}',

  timezone text not null default 'Europe/Dublin',

  -- Provisioned Twilio number. Null until onboarding completes.
  phone_number text unique,
  phone_number_sid text unique,

  -- Set once an automated test call has confirmed the customer's conditional
  -- forwarding actually works. Forwarding is configured on their handset and
  -- cannot be verified any other way.
  forwarding_verified_at timestamptz,

  -- Billing fields exist from day one even though nothing reads them until
  -- self-serve billing is built (docs/DECISIONS.md D5). This is what makes that
  -- phase additive rather than a data migration.
  plan text not null default 'starter'
    check (plan in ('starter', 'pro', 'business')),
  subscription_status text not null default 'incomplete'
    check (subscription_status in (
      'incomplete', 'trialing', 'active', 'past_due', 'canceled'
    )),
  stripe_customer_id text unique,
  stripe_subscription_id text unique,

  status text not null default 'onboarding'
    check (status in ('onboarding', 'active', 'suspended')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Membership is its own table rather than an owner_id on business, so that
-- multi-user teams (roadmap Phase 7) are additive rather than a restructure.
create table public.business_member (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'owner'
    check (role in ('owner', 'dispatcher', 'technician')),
  created_at timestamptz not null default now(),
  unique (business_id, user_id)
);

create index business_member_user_id_idx on public.business_member(user_id);
create index business_member_business_id_idx on public.business_member(business_id);

-- ---------------------------------------------------------------------------
-- Membership lookup used by every policy below
--
-- SECURITY DEFINER so the function can read business_member without recursing
-- into that table's own RLS policy. STABLE so Postgres evaluates it once per
-- statement rather than once per row.
-- ---------------------------------------------------------------------------

create or replace function public.is_business_member(target_business_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.business_member
    where business_id = target_business_id
      and user_id = (select auth.uid())
  );
$$;

-- ---------------------------------------------------------------------------
-- AI configuration
-- ---------------------------------------------------------------------------

create table public.business_profile (
  business_id uuid primary key references public.business(id) on delete cascade,

  -- Optional override of the default opening line.
  greeting text,

  tone text not null default 'Friendly, plain-spoken and brief. No jargon.',

  -- Defaults are deliberate. Quoting a price or promising an arrival time is
  -- how a receptionist costs a business money, and neither should depend on a
  -- customer remembering to switch it off.
  must_not text[] not null default array[
    'Never quote a price or estimate a cost.',
    'Never promise a specific arrival time.'
  ],

  fallback text not null default
    'I am not sure about that, but I will take your details and have someone come back to you.',

  closing_line text not null default
    'Thanks very much — someone will be in touch shortly.',

  confirmation_sms_template text not null default
    'Thanks {{caller_name}} — we have logged: {{job_type}}, {{location}}. {{business_name}} will be in touch shortly.',

  -- Hard stop so a confused or looping call cannot run up per-minute cost.
  max_call_seconds integer not null default 180
    check (max_call_seconds between 30 and 900),

  -- { "mon": { "open": "08:00", "close": "18:00" }, "sun": null }
  opening_hours jsonb not null default '{}'::jsonb,

  out_of_hours_behaviour text not null default 'answer_and_notify'
    check (out_of_hours_behaviour in (
      'answer_and_notify', 'answer_and_hold', 'do_not_answer'
    )),

  updated_at timestamptz not null default now()
);

-- The vocabulary the AI matches a caller's description against. This list is
-- the single biggest reason a plumber and a cleaner sound different without any
-- difference in code.
create table public.service (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,
  name text not null,
  emergency_eligible boolean not null default false,
  typical_urgency text not null default 'normal'
    check (typical_urgency in ('low', 'normal', 'high')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index service_business_id_idx on public.service(business_id);

create table public.qualification_question (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,
  prompt text not null,

  -- Which field of the lead this question fills. 'other' lands in lead.captured.
  captures text not null
    check (captures in (
      'job_type', 'location', 'urgency', 'contact_name', 'preferred_time', 'other'
    )),

  required boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index qualification_question_business_id_idx
  on public.qualification_question(business_id);

create table public.notification_rule (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,
  channel text not null check (channel in ('sms', 'email')),
  destination text not null,
  on_new_lead boolean not null default true,
  on_urgent_lead boolean not null default true,
  outside_hours boolean not null default true,
  created_at timestamptz not null default now()
);

create index notification_rule_business_id_idx
  on public.notification_rule(business_id);

-- ---------------------------------------------------------------------------
-- Calls and leads
--
-- Separate tables because they are not the same event. A call may produce no
-- lead at all (wrong number, immediate hangup), and keeping the call record
-- regardless is what makes "did it actually answer?" answerable.
-- ---------------------------------------------------------------------------

create table public.call (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,

  twilio_call_sid text unique,
  from_number text not null,
  to_number text not null,

  started_at timestamptz not null default now(),
  ended_at timestamptz,
  duration_seconds integer,

  recording_url text,

  -- [{ "role": "assistant" | "caller", "text": "...", "at": "..." }]
  transcript jsonb not null default '[]'::jsonb,

  status text not null default 'in_progress'
    check (status in ('in_progress', 'completed', 'failed', 'no_answer')),

  created_at timestamptz not null default now()
);

create index call_business_id_started_at_idx
  on public.call(business_id, started_at desc);

create table public.lead (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,
  call_id uuid references public.call(id) on delete set null,

  caller_number text not null,
  caller_name text,

  job_type text,
  location text,
  preferred_time text,

  urgency text not null default 'normal'
    check (urgency in ('low', 'normal', 'high')),

  -- Answers to questions whose `captures` is 'other'. A jsonb column rather
  -- than a captured_field table: the standard fields above are universal across
  -- trades, and a separate row-per-answer table would add a join to every read
  -- for data that is only ever displayed alongside its lead.
  captured jsonb not null default '{}'::jsonb,

  -- Flagged, never used to refuse a caller — the business may well travel.
  out_of_area boolean not null default false,

  status text not null default 'new'
    check (status in ('new', 'qualified', 'contacted', 'booked', 'completed', 'lost')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index lead_business_id_created_at_idx
  on public.lead(business_id, created_at desc);
create index lead_call_id_idx on public.lead(call_id);

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger business_set_updated_at
  before update on public.business
  for each row execute function public.set_updated_at();

create trigger business_profile_set_updated_at
  before update on public.business_profile
  for each row execute function public.set_updated_at();

create trigger lead_set_updated_at
  before update on public.lead
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row-level security
--
-- Enabled on every table. Server-side code that must write regardless of a user
-- session (the Twilio webhook handling a live call, the provisioning chain)
-- uses the service role key, which bypasses RLS by design.
-- ---------------------------------------------------------------------------

alter table public.business enable row level security;
alter table public.business_member enable row level security;
alter table public.business_profile enable row level security;
alter table public.service enable row level security;
alter table public.qualification_question enable row level security;
alter table public.notification_rule enable row level security;
alter table public.call enable row level security;
alter table public.lead enable row level security;

-- business: members read and update their own; creation goes through the
-- server, so there is deliberately no INSERT policy for end users.
create policy business_select_own on public.business
  for select using (public.is_business_member(id));

create policy business_update_own on public.business
  for update using (public.is_business_member(id))
  with check (public.is_business_member(id));

-- business_member: a user sees their own memberships. No self-service insert —
-- adding a member is a server-side operation so it can be authorised properly.
create policy business_member_select_own on public.business_member
  for select using (user_id = (select auth.uid()));

-- Configuration tables: members have full control over their own business.
create policy business_profile_all_own on public.business_profile
  for all using (public.is_business_member(business_id))
  with check (public.is_business_member(business_id));

create policy service_all_own on public.service
  for all using (public.is_business_member(business_id))
  with check (public.is_business_member(business_id));

create policy qualification_question_all_own on public.qualification_question
  for all using (public.is_business_member(business_id))
  with check (public.is_business_member(business_id));

create policy notification_rule_all_own on public.notification_rule
  for all using (public.is_business_member(business_id))
  with check (public.is_business_member(business_id));

-- Calls are written by the system, never by a user. Read-only.
create policy call_select_own on public.call
  for select using (public.is_business_member(business_id));

-- Leads are created by the system; owners read them and update their status as
-- they work them through the pipeline.
create policy lead_select_own on public.lead
  for select using (public.is_business_member(business_id));

create policy lead_update_own on public.lead
  for update using (public.is_business_member(business_id))
  with check (public.is_business_member(business_id));

-- ======================================================================
-- 20260731120100_bootstrap_business.sql
-- ======================================================================

-- Bootstrap a new business with a profile and a working questionnaire.
--
-- A trigger rather than application code, because business_profile is 1:1 and
-- required — the AI cannot answer a call without it. Making that an invariant
-- of the database means no provisioning path, present or future, can create a
-- business that is unable to take calls.
--
-- The default questions are deliberately industry-agnostic. They are also
-- deliberately *present*: docs/BUSINESS-PROFILE.md notes that an empty
-- questionnaire on day one is how onboarding gets abandoned. A business edits
-- these rather than authoring them from nothing.
--
-- Services are NOT seeded. They are inherently specific to the business, and a
-- wrong guess ("boiler repair" for a cleaning company) is worse than an empty
-- list the onboarding flow explicitly asks them to fill.

create or replace function public.bootstrap_business()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.business_profile (business_id)
  values (new.id);

  insert into public.qualification_question
    (business_id, prompt, captures, required, sort_order)
  values
    (new.id, 'Can you tell me what the job is?',        'job_type',       true,  1),
    (new.id, 'And whereabouts are you based?',          'location',       true,  2),
    (new.id, 'Is this an emergency, or can it wait?',   'urgency',        true,  3),
    (new.id, 'Can I take your name?',                   'contact_name',   true,  4),
    (new.id, 'When would suit you best?',               'preferred_time', false, 5);

  return new;
end;
$$;

create trigger business_bootstrap
  after insert on public.business
  for each row execute function public.bootstrap_business();

-- ======================================================================
-- 20260731120200_create_business_rpc.sql
-- ======================================================================

-- Creating a business is deliberately not an INSERT policy on public.business.
--
-- A business and its owning membership must be created together — a business
-- with no member is invisible to everyone and unrecoverable through the API,
-- and a client-side insert cannot guarantee the second statement runs. This
-- function makes the pair atomic.
--
-- SECURITY DEFINER, but it reads auth.uid() itself rather than accepting a user
-- id, so it cannot be called to create a business on someone else's behalf.

-- `selected_plan` records which plan the customer clicked, nothing more. It
-- grants no entitlement: subscription_status is the gate, and only the Stripe
-- webhook (service role) may set it. That separation matters because a user can
-- edit their own auth metadata, so the plan arriving here is an expression of
-- intent that must never be trusted as proof of payment.
create or replace function public.create_business_for_current_user(
  business_name text,
  selected_plan text default 'starter'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := (select auth.uid());
  new_business_id uuid;
  safe_plan text := coalesce(selected_plan, 'starter');
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if business_name is null or length(trim(business_name)) = 0 then
    raise exception 'Business name is required';
  end if;

  if safe_plan not in ('starter', 'pro', 'business') then
    safe_plan := 'starter';
  end if;

  -- One business per user until team accounts exist (roadmap Phase 7). Returning
  -- the existing id rather than raising makes this safe to call on every page
  -- load, which is what lets onboarding work whether or not email confirmation
  -- is enabled on the project.
  select business_id into new_business_id
  from public.business_member
  where user_id = current_user_id
  limit 1;

  if new_business_id is not null then
    return new_business_id;
  end if;

  insert into public.business (name, plan)
  values (trim(business_name), safe_plan)
  returning id into new_business_id;

  insert into public.business_member (business_id, user_id, role)
  values (new_business_id, current_user_id, 'owner');

  return new_business_id;
end;
$$;

revoke all on function public.create_business_for_current_user(text, text) from public;
grant execute on function public.create_business_for_current_user(text, text) to authenticated;

-- ======================================================================
-- 20260731120300_call_notified_at.sql
-- ======================================================================

-- Track notification separately from call completion.
--
-- These were conflated, and the bug it caused was silent and total: the turn
-- handler marks a call completed when the conversation ends, and the status
-- callback treated "already completed" as "already dealt with" — so it skipped
-- notifications for every normally-finished call. The confirmation text and the
-- job alert, which are the entire point of the product, were never sent.
--
-- A call being over and its notifications having gone out are different facts
-- and now have different columns.

alter table public.call
  add column notified_at timestamptz;

comment on column public.call.notified_at is
  'When the confirmation SMS and owner alert were sent. Claimed atomically so a retried Twilio status callback cannot notify twice.';

-- ======================================================================
-- 20260731120400_atomic_replacements.sql
-- ======================================================================

-- Replace-in-place operations that must not be able to half-fail.
--
-- Both of these were previously a DELETE followed by an INSERT from the
-- application, as two separate round trips. A failure between them — a dropped
-- connection, a timeout, a constraint violation — left the business with
-- nothing: no services, so the receptionist has no vocabulary to match a caller
-- against; or no notification rule, so qualified jobs go nowhere at all.
--
-- Neither failure is visible to the customer. They would simply find that the
-- product had quietly stopped working properly.
--
-- A plpgsql function runs in a single transaction, so the delete and insert
-- either both happen or neither does.
--
-- SECURITY INVOKER (the default) is deliberate: row-level security still
-- applies, so passing another business's id changes nothing that isn't yours.

create or replace function public.replace_services(
  target_business_id uuid,
  service_names text[],
  emergency_names text[]
)
returns void
language plpgsql
set search_path = public
as $$
declare
  service_name text;
  sort_position integer := 0;
  is_emergency boolean;
begin
  delete from public.service where business_id = target_business_id;

  foreach service_name in array coalesce(service_names, '{}')
  loop
    sort_position := sort_position + 1;

    is_emergency := exists (
      select 1
      from unnest(coalesce(emergency_names, '{}')) as candidate
      where lower(candidate) = lower(service_name)
    );

    insert into public.service
      (business_id, name, emergency_eligible, typical_urgency, sort_order)
    values (
      target_business_id,
      service_name,
      is_emergency,
      case when is_emergency then 'high' else 'normal' end,
      sort_position
    );
  end loop;
end;
$$;

create or replace function public.replace_sms_notification(
  target_business_id uuid,
  sms_destination text
)
returns void
language plpgsql
set search_path = public
as $$
begin
  delete from public.notification_rule
  where business_id = target_business_id
    and channel = 'sms';

  insert into public.notification_rule
    (business_id, channel, destination, on_new_lead, on_urgent_lead, outside_hours)
  values (target_business_id, 'sms', sms_destination, true, true, true);
end;
$$;

revoke all on function public.replace_services(uuid, text[], text[]) from public;
grant execute on function public.replace_services(uuid, text[], text[]) to authenticated;

revoke all on function public.replace_sms_notification(uuid, text) from public;
grant execute on function public.replace_sms_notification(uuid, text) to authenticated;

-- ======================================================================
-- 20260731120500_restrict_business_columns.sql
-- ======================================================================

-- Stop a customer granting themselves a free subscription.
--
-- Row-level security gates which ROWS a user may touch, never which COLUMNS.
-- The business_update_own policy correctly limits a user to their own business,
-- and then let them write every column of it — including plan,
-- subscription_status and status.
--
-- Since Supabase grants table privileges to `authenticated` by default, any
-- signed-in customer could have run this from the browser with the publishable
-- key and their own session:
--
--   supabase.from('business').update({
--     plan: 'business',
--     subscription_status: 'active',
--     status: 'active'
--   })
--
-- RLS permits it, the CHECK constraints permit those values, and the result is
-- unlimited Business-tier service for free. Every guarantee about entitlement
-- coming only from the Stripe webhook was defeated by this one policy.
--
-- Column-level GRANTs are the missing half: RLS decides the row, grants decide
-- the column. A customer may edit what describes their business; everything
-- that decides what they are entitled to, or how calls reach them, is writable
-- only by the service role.

revoke update on public.business from authenticated;

grant update (
  name,
  industry_label,
  service_area,
  timezone
) on public.business to authenticated;

-- Leads are created by the system. An owner works them through the pipeline, so
-- status is theirs to change — but the captured details are evidence of what a
-- caller actually said and should not be quietly rewritten.
revoke update on public.lead from authenticated;

grant update (status) on public.lead to authenticated;

-- ======================================================================
-- 20260731120600_sms_abuse_limits.sql
-- ======================================================================

-- Contain what one customer can do to every other customer.
--
-- Outbound SMS goes through a single ComReg-registered sender ID shared by the
-- whole platform, because registration is per-organisation and cannot be
-- automated per business. That makes it shared fate: the confirmation template
-- is customer-writable, has no UI (so the API is the only path and there is no
-- form to validate in), and its contents are delivered to third parties under
-- FlowPilot's name.
--
-- One customer sending smishing through it gets the registration revoked, and
-- SMS stops working for everyone. Ireland's Sender ID Registry exists
-- specifically to police that, so this is not a hypothetical failure mode.
--
-- These constraints live in the database rather than in application code
-- because RLS already permits direct API writes — anything enforced only in a
-- form is enforced only for people who use the form.

alter table public.business_profile
  add constraint confirmation_sms_template_length
    check (length(confirmation_sms_template) <= 320);

-- Links are the mechanism of virtually all smishing. A confirmation of details
-- the caller just gave over the phone has no legitimate need for one, and
-- allowing them is what gets a sender ID revoked.
alter table public.business_profile
  add constraint confirmation_sms_template_no_links
    check (confirmation_sms_template !~* '(https?://|www\.)');

-- Every notification rule is another SMS per lead, billed to FlowPilot. With
-- no cap, a customer could add hundreds and turn the platform into an SMS pump
-- at our expense. Five covers an owner, an office and a couple of vans.
create or replace function public.enforce_notification_rule_limit()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  existing_count integer;
begin
  select count(*) into existing_count
  from public.notification_rule
  where business_id = new.business_id;

  if existing_count >= 5 then
    raise exception 'A business can have at most 5 notification rules';
  end if;

  return new;
end;
$$;

create trigger notification_rule_limit
  before insert on public.notification_rule
  for each row execute function public.enforce_notification_rule_limit();

-- ======================================================================
-- 20260731120700_trial_reminders.sql
-- ======================================================================

-- Track which trial reminders have been sent.
--
-- The trial now genuinely expires, which means a customer's receptionist stops
-- answering on a schedule. Without a warning, the first they know of it is a
-- quiet week and a customer who rang someone else — and the dashboard banner
-- only helps people who happen to log in, which is exactly the group least
-- likely to notice.
--
-- A single column rather than a table of sends: there are only ever two
-- reminders per trial, and the question being asked is "what was the last thing
-- we told them", not "what is the history".

alter table public.business
  add column trial_reminder_stage text
    check (trial_reminder_stage in ('ending_soon', 'expired'));

comment on column public.business.trial_reminder_stage is
  'Last trial reminder sent, so the daily job cannot send the same one twice.';

-- Only the service role may write it: it is set by a scheduled job, and a
-- customer clearing it would make the job email them again.
revoke update on public.business from authenticated;

grant update (
  name,
  industry_label,
  service_area,
  timezone
) on public.business to authenticated;

-- ======================================================================
-- 20260731120800_demo_usage.sql
-- ======================================================================

-- Rate limiting for the public demo on the marketing site.
--
-- The demo calls a paid model from a page anyone can load, so it needs a cap
-- that survives across serverless instances. An in-memory counter would reset
-- on every cold start, which on Vercel means it barely limits anything.
--
-- Stores a hash of the caller's IP, never the address itself. The point is to
-- count requests, and a hash counts just as well without keeping a record of
-- who visited the site.

create table public.demo_usage (
  ip_hash text primary key,
  request_count integer not null default 0,
  window_started_at timestamptz not null default now()
);

-- Written only by the demo endpoint using the service role. No policy grants
-- access to anyone else; RLS with no policy denies everything, which is exactly
-- right for a table no user should ever read.
alter table public.demo_usage enable row level security;

create index demo_usage_window_idx on public.demo_usage(window_started_at);

comment on table public.demo_usage is
  'Rate limiting for the public marketing demo. Hashed IPs only, pruned by age.';

-- ======================================================================
-- 20260806120000_drop_recording_url.sql
-- ======================================================================

-- Removes a column that promised something FlowPilot does not do.
--
-- call.recording_url has existed since the initial schema and has never been
-- written to. No Twilio <Record> verb is used anywhere in the codebase: calls
-- are transcribed by <Gather input="speech">, not recorded. Every row is null
-- and always has been.
--
-- Dropped rather than left alone because of what it implies. docs/DATA-PROCESSING.md
-- tells anyone auditing this product that no audio is captured, and a column
-- called recording_url is precisely the thing that contradicts that at a glance
-- — to a solicitor, a data protection officer, or an engineer who assumes the
-- feature exists and starts relying on it. The schema should say what is true.
--
-- Reversible: if call recording is ever built, adding a column back is trivial,
-- and doing so deliberately is better than inheriting one nobody chose.

alter table public.call drop column if exists recording_url;

