-- FlowPilot — all migrations, in order.
--
-- Generated by scripts/build-combined-migration.mjs. Do not edit directly;
-- edit the files in supabase/migrations and regenerate.
--
-- Paste the whole file into the Supabase SQL Editor and run it once.
-- Intended for a fresh project — it is not written to be re-run.

-- ======================================================================
-- 20260731120000_initial_schema.sql
-- ======================================================================

-- FlowPilot initial schema
--
-- Multi-tenant from the first table. Every tenant-scoped table carries
-- business_id and ships with a row-level security policy in this same
-- migration — see docs/DECISIONS.md D3. Retrofitting RLS later is a migration
-- with a data-exposure window, and there is no reason to accept that when it is
-- free now.
--
-- Status and role columns use text + CHECK rather than Postgres enums.
-- Enums require an ALTER TYPE to extend and cannot drop values at all, which
-- makes every future plan tier or lead state a schema migration. The CHECK
-- constraint gives the same integrity with a far cheaper change path.

-- ---------------------------------------------------------------------------
-- Tenancy
-- ---------------------------------------------------------------------------

create table public.business (
  id uuid primary key default gen_random_uuid(),

  name text not null,

  -- Marketing and reporting only. Nothing in the application may branch on
  -- this — see docs/BUSINESS-PROFILE.md. A plumber and a cleaner differ in
  -- their configured data, never in a code path keyed off this column.
  industry_label text,

  -- Places served. Used to flag out-of-area jobs, never to refuse a caller.
  service_area text[] not null default '{}',

  timezone text not null default 'Europe/Dublin',

  -- Provisioned Twilio number. Null until onboarding completes.
  phone_number text unique,
  phone_number_sid text unique,

  -- Set once an automated test call has confirmed the customer's conditional
  -- forwarding actually works. Forwarding is configured on their handset and
  -- cannot be verified any other way.
  forwarding_verified_at timestamptz,

  -- Billing fields exist from day one even though nothing reads them until
  -- self-serve billing is built (docs/DECISIONS.md D5). This is what makes that
  -- phase additive rather than a data migration.
  plan text not null default 'starter'
    check (plan in ('starter', 'pro', 'business')),
  subscription_status text not null default 'incomplete'
    check (subscription_status in (
      'incomplete', 'trialing', 'active', 'past_due', 'canceled'
    )),
  stripe_customer_id text unique,
  stripe_subscription_id text unique,

  status text not null default 'onboarding'
    check (status in ('onboarding', 'active', 'suspended')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Membership is its own table rather than an owner_id on business, so that
-- multi-user teams (roadmap Phase 7) are additive rather than a restructure.
create table public.business_member (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'owner'
    check (role in ('owner', 'dispatcher', 'technician')),
  created_at timestamptz not null default now(),
  unique (business_id, user_id)
);

create index business_member_user_id_idx on public.business_member(user_id);
create index business_member_business_id_idx on public.business_member(business_id);

-- ---------------------------------------------------------------------------
-- Membership lookup used by every policy below
--
-- SECURITY DEFINER so the function can read business_member without recursing
-- into that table's own RLS policy. STABLE so Postgres evaluates it once per
-- statement rather than once per row.
-- ---------------------------------------------------------------------------

create or replace function public.is_business_member(target_business_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.business_member
    where business_id = target_business_id
      and user_id = (select auth.uid())
  );
$$;

-- ---------------------------------------------------------------------------
-- AI configuration
-- ---------------------------------------------------------------------------

create table public.business_profile (
  business_id uuid primary key references public.business(id) on delete cascade,

  -- Optional override of the default opening line.
  greeting text,

  tone text not null default 'Friendly, plain-spoken and brief. No jargon.',

  -- Defaults are deliberate. Quoting a price or promising an arrival time is
  -- how a receptionist costs a business money, and neither should depend on a
  -- customer remembering to switch it off.
  must_not text[] not null default array[
    'Never quote a price or estimate a cost.',
    'Never promise a specific arrival time.'
  ],

  fallback text not null default
    'I am not sure about that, but I will take your details and have someone come back to you.',

  closing_line text not null default
    'Thanks very much — someone will be in touch shortly.',

  confirmation_sms_template text not null default
    'Thanks {{caller_name}} — we have logged: {{job_type}}, {{location}}. {{business_name}} will be in touch shortly.',

  -- Hard stop so a confused or looping call cannot run up per-minute cost.
  max_call_seconds integer not null default 180
    check (max_call_seconds between 30 and 900),

  -- { "mon": { "open": "08:00", "close": "18:00" }, "sun": null }
  opening_hours jsonb not null default '{}'::jsonb,

  out_of_hours_behaviour text not null default 'answer_and_notify'
    check (out_of_hours_behaviour in (
      'answer_and_notify', 'answer_and_hold', 'do_not_answer'
    )),

  updated_at timestamptz not null default now()
);

-- The vocabulary the AI matches a caller's description against. This list is
-- the single biggest reason a plumber and a cleaner sound different without any
-- difference in code.
create table public.service (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,
  name text not null,
  emergency_eligible boolean not null default false,
  typical_urgency text not null default 'normal'
    check (typical_urgency in ('low', 'normal', 'high')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index service_business_id_idx on public.service(business_id);

create table public.qualification_question (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,
  prompt text not null,

  -- Which field of the lead this question fills. 'other' lands in lead.captured.
  captures text not null
    check (captures in (
      'job_type', 'location', 'urgency', 'contact_name', 'preferred_time', 'other'
    )),

  required boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index qualification_question_business_id_idx
  on public.qualification_question(business_id);

create table public.notification_rule (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,
  channel text not null check (channel in ('sms', 'email')),
  destination text not null,
  on_new_lead boolean not null default true,
  on_urgent_lead boolean not null default true,
  outside_hours boolean not null default true,
  created_at timestamptz not null default now()
);

create index notification_rule_business_id_idx
  on public.notification_rule(business_id);

-- ---------------------------------------------------------------------------
-- Calls and leads
--
-- Separate tables because they are not the same event. A call may produce no
-- lead at all (wrong number, immediate hangup), and keeping the call record
-- regardless is what makes "did it actually answer?" answerable.
-- ---------------------------------------------------------------------------

create table public.call (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,

  twilio_call_sid text unique,
  from_number text not null,
  to_number text not null,

  started_at timestamptz not null default now(),
  ended_at timestamptz,
  duration_seconds integer,

  recording_url text,

  -- [{ "role": "assistant" | "caller", "text": "...", "at": "..." }]
  transcript jsonb not null default '[]'::jsonb,

  status text not null default 'in_progress'
    check (status in ('in_progress', 'completed', 'failed', 'no_answer')),

  created_at timestamptz not null default now()
);

create index call_business_id_started_at_idx
  on public.call(business_id, started_at desc);

create table public.lead (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,
  call_id uuid references public.call(id) on delete set null,

  caller_number text not null,
  caller_name text,

  job_type text,
  location text,
  preferred_time text,

  urgency text not null default 'normal'
    check (urgency in ('low', 'normal', 'high')),

  -- Answers to questions whose `captures` is 'other'. A jsonb column rather
  -- than a captured_field table: the standard fields above are universal across
  -- trades, and a separate row-per-answer table would add a join to every read
  -- for data that is only ever displayed alongside its lead.
  captured jsonb not null default '{}'::jsonb,

  -- Flagged, never used to refuse a caller — the business may well travel.
  out_of_area boolean not null default false,

  status text not null default 'new'
    check (status in ('new', 'qualified', 'contacted', 'booked', 'completed', 'lost')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index lead_business_id_created_at_idx
  on public.lead(business_id, created_at desc);
create index lead_call_id_idx on public.lead(call_id);

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger business_set_updated_at
  before update on public.business
  for each row execute function public.set_updated_at();

create trigger business_profile_set_updated_at
  before update on public.business_profile
  for each row execute function public.set_updated_at();

create trigger lead_set_updated_at
  before update on public.lead
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row-level security
--
-- Enabled on every table. Server-side code that must write regardless of a user
-- session (the Twilio webhook handling a live call, the provisioning chain)
-- uses the service role key, which bypasses RLS by design.
-- ---------------------------------------------------------------------------

alter table public.business enable row level security;
alter table public.business_member enable row level security;
alter table public.business_profile enable row level security;
alter table public.service enable row level security;
alter table public.qualification_question enable row level security;
alter table public.notification_rule enable row level security;
alter table public.call enable row level security;
alter table public.lead enable row level security;

-- business: members read and update their own; creation goes through the
-- server, so there is deliberately no INSERT policy for end users.
create policy business_select_own on public.business
  for select using (public.is_business_member(id));

create policy business_update_own on public.business
  for update using (public.is_business_member(id))
  with check (public.is_business_member(id));

-- business_member: a user sees their own memberships. No self-service insert —
-- adding a member is a server-side operation so it can be authorised properly.
create policy business_member_select_own on public.business_member
  for select using (user_id = (select auth.uid()));

-- Configuration tables: members have full control over their own business.
create policy business_profile_all_own on public.business_profile
  for all using (public.is_business_member(business_id))
  with check (public.is_business_member(business_id));

create policy service_all_own on public.service
  for all using (public.is_business_member(business_id))
  with check (public.is_business_member(business_id));

create policy qualification_question_all_own on public.qualification_question
  for all using (public.is_business_member(business_id))
  with check (public.is_business_member(business_id));

create policy notification_rule_all_own on public.notification_rule
  for all using (public.is_business_member(business_id))
  with check (public.is_business_member(business_id));

-- Calls are written by the system, never by a user. Read-only.
create policy call_select_own on public.call
  for select using (public.is_business_member(business_id));

-- Leads are created by the system; owners read them and update their status as
-- they work them through the pipeline.
create policy lead_select_own on public.lead
  for select using (public.is_business_member(business_id));

create policy lead_update_own on public.lead
  for update using (public.is_business_member(business_id))
  with check (public.is_business_member(business_id));

-- ======================================================================
-- 20260731120100_bootstrap_business.sql
-- ======================================================================

-- Bootstrap a new business with a profile and a working questionnaire.
--
-- A trigger rather than application code, because business_profile is 1:1 and
-- required — the AI cannot answer a call without it. Making that an invariant
-- of the database means no provisioning path, present or future, can create a
-- business that is unable to take calls.
--
-- The default questions are deliberately industry-agnostic. They are also
-- deliberately *present*: docs/BUSINESS-PROFILE.md notes that an empty
-- questionnaire on day one is how onboarding gets abandoned. A business edits
-- these rather than authoring them from nothing.
--
-- Services are NOT seeded. They are inherently specific to the business, and a
-- wrong guess ("boiler repair" for a cleaning company) is worse than an empty
-- list the onboarding flow explicitly asks them to fill.

create or replace function public.bootstrap_business()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.business_profile (business_id)
  values (new.id);

  insert into public.qualification_question
    (business_id, prompt, captures, required, sort_order)
  values
    (new.id, 'Can you tell me what the job is?',        'job_type',       true,  1),
    (new.id, 'And whereabouts are you based?',          'location',       true,  2),
    (new.id, 'Is this an emergency, or can it wait?',   'urgency',        true,  3),
    (new.id, 'Can I take your name?',                   'contact_name',   true,  4),
    (new.id, 'When would suit you best?',               'preferred_time', false, 5);

  return new;
end;
$$;

create trigger business_bootstrap
  after insert on public.business
  for each row execute function public.bootstrap_business();

-- ======================================================================
-- 20260731120200_create_business_rpc.sql
-- ======================================================================

-- Creating a business is deliberately not an INSERT policy on public.business.
--
-- A business and its owning membership must be created together — a business
-- with no member is invisible to everyone and unrecoverable through the API,
-- and a client-side insert cannot guarantee the second statement runs. This
-- function makes the pair atomic.
--
-- SECURITY DEFINER, but it reads auth.uid() itself rather than accepting a user
-- id, so it cannot be called to create a business on someone else's behalf.

-- `selected_plan` records which plan the customer clicked, nothing more. It
-- grants no entitlement: subscription_status is the gate, and only the Stripe
-- webhook (service role) may set it. That separation matters because a user can
-- edit their own auth metadata, so the plan arriving here is an expression of
-- intent that must never be trusted as proof of payment.
create or replace function public.create_business_for_current_user(
  business_name text,
  selected_plan text default 'starter'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := (select auth.uid());
  new_business_id uuid;
  safe_plan text := coalesce(selected_plan, 'starter');
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if business_name is null or length(trim(business_name)) = 0 then
    raise exception 'Business name is required';
  end if;

  if safe_plan not in ('starter', 'pro', 'business') then
    safe_plan := 'starter';
  end if;

  -- One business per user until team accounts exist (roadmap Phase 7). Returning
  -- the existing id rather than raising makes this safe to call on every page
  -- load, which is what lets onboarding work whether or not email confirmation
  -- is enabled on the project.
  select business_id into new_business_id
  from public.business_member
  where user_id = current_user_id
  limit 1;

  if new_business_id is not null then
    return new_business_id;
  end if;

  insert into public.business (name, plan)
  values (trim(business_name), safe_plan)
  returning id into new_business_id;

  insert into public.business_member (business_id, user_id, role)
  values (new_business_id, current_user_id, 'owner');

  return new_business_id;
end;
$$;

revoke all on function public.create_business_for_current_user(text, text) from public;
grant execute on function public.create_business_for_current_user(text, text) to authenticated;

-- ======================================================================
-- 20260731120300_call_notified_at.sql
-- ======================================================================

-- Track notification separately from call completion.
--
-- These were conflated, and the bug it caused was silent and total: the turn
-- handler marks a call completed when the conversation ends, and the status
-- callback treated "already completed" as "already dealt with" — so it skipped
-- notifications for every normally-finished call. The confirmation text and the
-- job alert, which are the entire point of the product, were never sent.
--
-- A call being over and its notifications having gone out are different facts
-- and now have different columns.

alter table public.call
  add column notified_at timestamptz;

comment on column public.call.notified_at is
  'When the confirmation SMS and owner alert were sent. Claimed atomically so a retried Twilio status callback cannot notify twice.';

-- ======================================================================
-- 20260731120400_atomic_replacements.sql
-- ======================================================================

-- Replace-in-place operations that must not be able to half-fail.
--
-- Both of these were previously a DELETE followed by an INSERT from the
-- application, as two separate round trips. A failure between them — a dropped
-- connection, a timeout, a constraint violation — left the business with
-- nothing: no services, so the receptionist has no vocabulary to match a caller
-- against; or no notification rule, so qualified jobs go nowhere at all.
--
-- Neither failure is visible to the customer. They would simply find that the
-- product had quietly stopped working properly.
--
-- A plpgsql function runs in a single transaction, so the delete and insert
-- either both happen or neither does.
--
-- SECURITY INVOKER (the default) is deliberate: row-level security still
-- applies, so passing another business's id changes nothing that isn't yours.

create or replace function public.replace_services(
  target_business_id uuid,
  service_names text[],
  emergency_names text[]
)
returns void
language plpgsql
set search_path = public
as $$
declare
  service_name text;
  sort_position integer := 0;
  is_emergency boolean;
begin
  delete from public.service where business_id = target_business_id;

  foreach service_name in array coalesce(service_names, '{}')
  loop
    sort_position := sort_position + 1;

    is_emergency := exists (
      select 1
      from unnest(coalesce(emergency_names, '{}')) as candidate
      where lower(candidate) = lower(service_name)
    );

    insert into public.service
      (business_id, name, emergency_eligible, typical_urgency, sort_order)
    values (
      target_business_id,
      service_name,
      is_emergency,
      case when is_emergency then 'high' else 'normal' end,
      sort_position
    );
  end loop;
end;
$$;

create or replace function public.replace_sms_notification(
  target_business_id uuid,
  sms_destination text
)
returns void
language plpgsql
set search_path = public
as $$
begin
  delete from public.notification_rule
  where business_id = target_business_id
    and channel = 'sms';

  insert into public.notification_rule
    (business_id, channel, destination, on_new_lead, on_urgent_lead, outside_hours)
  values (target_business_id, 'sms', sms_destination, true, true, true);
end;
$$;

revoke all on function public.replace_services(uuid, text[], text[]) from public;
grant execute on function public.replace_services(uuid, text[], text[]) to authenticated;

revoke all on function public.replace_sms_notification(uuid, text) from public;
grant execute on function public.replace_sms_notification(uuid, text) to authenticated;

-- ======================================================================
-- 20260731120500_restrict_business_columns.sql
-- ======================================================================

-- Stop a customer granting themselves a free subscription.
--
-- Row-level security gates which ROWS a user may touch, never which COLUMNS.
-- The business_update_own policy correctly limits a user to their own business,
-- and then let them write every column of it — including plan,
-- subscription_status and status.
--
-- Since Supabase grants table privileges to `authenticated` by default, any
-- signed-in customer could have run this from the browser with the publishable
-- key and their own session:
--
--   supabase.from('business').update({
--     plan: 'business',
--     subscription_status: 'active',
--     status: 'active'
--   })
--
-- RLS permits it, the CHECK constraints permit those values, and the result is
-- unlimited Business-tier service for free. Every guarantee about entitlement
-- coming only from the Stripe webhook was defeated by this one policy.
--
-- Column-level GRANTs are the missing half: RLS decides the row, grants decide
-- the column. A customer may edit what describes their business; everything
-- that decides what they are entitled to, or how calls reach them, is writable
-- only by the service role.

revoke update on public.business from authenticated;

grant update (
  name,
  industry_label,
  service_area,
  timezone
) on public.business to authenticated;

-- Leads are created by the system. An owner works them through the pipeline, so
-- status is theirs to change — but the captured details are evidence of what a
-- caller actually said and should not be quietly rewritten.
revoke update on public.lead from authenticated;

grant update (status) on public.lead to authenticated;

-- ======================================================================
-- 20260731120600_sms_abuse_limits.sql
-- ======================================================================

-- Contain what one customer can do to every other customer.
--
-- Outbound SMS goes through a single ComReg-registered sender ID shared by the
-- whole platform, because registration is per-organisation and cannot be
-- automated per business. That makes it shared fate: the confirmation template
-- is customer-writable, has no UI (so the API is the only path and there is no
-- form to validate in), and its contents are delivered to third parties under
-- FlowPilot's name.
--
-- One customer sending smishing through it gets the registration revoked, and
-- SMS stops working for everyone. Ireland's Sender ID Registry exists
-- specifically to police that, so this is not a hypothetical failure mode.
--
-- These constraints live in the database rather than in application code
-- because RLS already permits direct API writes — anything enforced only in a
-- form is enforced only for people who use the form.

alter table public.business_profile
  add constraint confirmation_sms_template_length
    check (length(confirmation_sms_template) <= 320);

-- Links are the mechanism of virtually all smishing. A confirmation of details
-- the caller just gave over the phone has no legitimate need for one, and
-- allowing them is what gets a sender ID revoked.
alter table public.business_profile
  add constraint confirmation_sms_template_no_links
    check (confirmation_sms_template !~* '(https?://|www\.)');

-- Every notification rule is another SMS per lead, billed to FlowPilot. With
-- no cap, a customer could add hundreds and turn the platform into an SMS pump
-- at our expense. Five covers an owner, an office and a couple of vans.
create or replace function public.enforce_notification_rule_limit()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  existing_count integer;
begin
  select count(*) into existing_count
  from public.notification_rule
  where business_id = new.business_id;

  if existing_count >= 5 then
    raise exception 'A business can have at most 5 notification rules';
  end if;

  return new;
end;
$$;

create trigger notification_rule_limit
  before insert on public.notification_rule
  for each row execute function public.enforce_notification_rule_limit();

-- ======================================================================
-- 20260731120700_trial_reminders.sql
-- ======================================================================

-- Track which trial reminders have been sent.
--
-- The trial now genuinely expires, which means a customer's receptionist stops
-- answering on a schedule. Without a warning, the first they know of it is a
-- quiet week and a customer who rang someone else — and the dashboard banner
-- only helps people who happen to log in, which is exactly the group least
-- likely to notice.
--
-- A single column rather than a table of sends: there are only ever two
-- reminders per trial, and the question being asked is "what was the last thing
-- we told them", not "what is the history".

alter table public.business
  add column trial_reminder_stage text
    check (trial_reminder_stage in ('ending_soon', 'expired'));

comment on column public.business.trial_reminder_stage is
  'Last trial reminder sent, so the daily job cannot send the same one twice.';

-- Only the service role may write it: it is set by a scheduled job, and a
-- customer clearing it would make the job email them again.
revoke update on public.business from authenticated;

grant update (
  name,
  industry_label,
  service_area,
  timezone
) on public.business to authenticated;

-- ======================================================================
-- 20260731120800_demo_usage.sql
-- ======================================================================

-- Rate limiting for the public demo on the marketing site.
--
-- The demo calls a paid model from a page anyone can load, so it needs a cap
-- that survives across serverless instances. An in-memory counter would reset
-- on every cold start, which on Vercel means it barely limits anything.
--
-- Stores a hash of the caller's IP, never the address itself. The point is to
-- count requests, and a hash counts just as well without keeping a record of
-- who visited the site.

create table public.demo_usage (
  ip_hash text primary key,
  request_count integer not null default 0,
  window_started_at timestamptz not null default now()
);

-- Written only by the demo endpoint using the service role. No policy grants
-- access to anyone else; RLS with no policy denies everything, which is exactly
-- right for a table no user should ever read.
alter table public.demo_usage enable row level security;

create index demo_usage_window_idx on public.demo_usage(window_started_at);

comment on table public.demo_usage is
  'Rate limiting for the public marketing demo. Hashed IPs only, pruned by age.';

-- ======================================================================
-- 20260806120000_drop_recording_url.sql
-- ======================================================================

-- Removes a column that promised something FlowPilot does not do.
--
-- call.recording_url has existed since the initial schema and has never been
-- written to. No Twilio <Record> verb is used anywhere in the codebase: calls
-- are transcribed by <Gather input="speech">, not recorded. Every row is null
-- and always has been.
--
-- Dropped rather than left alone because of what it implies. docs/DATA-PROCESSING.md
-- tells anyone auditing this product that no audio is captured, and a column
-- called recording_url is precisely the thing that contradicts that at a glance
-- — to a solicitor, a data protection officer, or an engineer who assumes the
-- feature exists and starts relying on it. The schema should say what is true.
--
-- Reversible: if call recording is ever built, adding a column back is trivial,
-- and doing so deliberately is better than inheriting one nobody chose.

alter table public.call drop column if exists recording_url;

-- ======================================================================
-- 20260809120000_ask_when_not_whether_urgent.sql
-- ======================================================================

-- Asks when the job needs doing, before asking whether it's an emergency.
--
-- The default questions a new business got were built emergency-first:
--
--   3. "Is this an emergency, or can it wait?"  urgency         REQUIRED
--   5. "When would suit you best?"              preferred_time  optional
--
-- That is the wrong shape for the work these businesses actually do. Most of it
-- is planned — a rewire booked for a fortnight's time, a bathroom in March, a
-- job someone wants done before the in-laws visit. For a planned job the date is
-- the field that decides whether you can take it, and it was the one field the
-- receptionist was allowed to skip. Meanwhile every caller was asked to classify
-- their own job as an emergency, which is a question that only makes sense to a
-- business that sells emergency call-outs.
--
-- So they swap. Timing becomes required and is asked third, while the caller is
-- still describing the job. Urgency stays — a burst pipe genuinely is urgent and
-- the notification rules still route on it — but it moves last and becomes
-- optional, which is what it is: useful when it comes up, not worth interrogating
-- someone about.
--
-- lead.urgency is `not null default 'normal'`, so a call that never establishes
-- urgency still writes a valid row and still notifies. Nothing downstream needs
-- to change.
--
-- New businesses only. Existing rows are left alone deliberately: a business may
-- have edited its own questions in settings, and overwriting somebody's wording
-- to correct a default we shipped would be a worse trespass than the default.

create or replace function public.handle_new_business()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.business_profile (business_id)
  values (new.id);

  insert into public.qualification_question
    (business_id, prompt, captures, required, sort_order)
  values
    (new.id, 'Can you tell me what the job is?',          'job_type',       true,  1),
    (new.id, 'And whereabouts are you based?',            'location',       true,  2),
    (new.id, 'When are you hoping to get it done?',       'preferred_time', true,  3),
    (new.id, 'Can I take your name?',                     'contact_name',   true,  4),
    (new.id, 'Is it urgent, or can it wait?',             'urgency',        false, 5);

  return new;
end;
$$;

-- ======================================================================
-- 20260809140000_call_delivered_at.sql
-- ======================================================================

-- Records whether a job actually reached the owner, not just that we tried.
--
-- `notified_at` is claimed atomically *before* anything is sent, which is the
-- right way to stop a retried Twilio status callback texting somebody twice. But
-- it is written whether or not a single message goes out, and its own comment
-- claimed it recorded "when the confirmation SMS and owner alert were sent".
-- That is not what it holds. If every channel fails, notified_at is set, nothing
-- retries, and any operator reading the row concludes the owner was told.
--
-- That gap is not theoretical. Email is the only regulator-free channel and is
-- not configured in production, so SMS is currently the single path to a
-- customer — and if an unregistered sender ID is rejected in Ireland, every job
-- fails to deliver while every row says otherwise. The first anyone would know
-- is a customer ringing to ask why FlowPilot has gone quiet, and there would be
-- nothing in the database to confirm or deny it.
--
-- Two columns for two facts:
--   notified_at  — we took the lock and attempted delivery (dedup)
--   delivered_at — at least one channel actually accepted the message
--
-- Deliberately not a retry mechanism. Retrying safely means knowing which
-- channel succeeded, and a wrong retry double-texts a customer, which is worse
-- than a missed one. This makes the failure visible first; acting on it is a
-- decision to take with evidence rather than a guess to build now.

alter table public.call
  add column if not exists delivered_at timestamptz;

comment on column public.call.notified_at is
  'When delivery was attempted. Claimed atomically before sending, so a retried Twilio status callback cannot notify twice. NOT proof anything arrived — see delivered_at.';

comment on column public.call.delivered_at is
  'When at least one notification channel accepted a message for this call. Null alongside a set notified_at means the job was captured and reached nobody.';

-- ======================================================================
-- 20260809160000_lead_short_code.sql
-- ======================================================================

-- A short code per lead, so the job alert can carry a link somebody can tap.
--
-- The alert text told a tradesperson a job existed and then left them to find
-- it: no way to act on it, and no route from the text to the job. Keeping track
-- meant remembering, unprompted, to open a website, while the text scrolled away
-- under WhatsApp. The text is the alert, the dashboard is the list of what you
-- still owe people, and this is what joins them.
--
-- Short rather than the uuid because this rides in an SMS. A GSM-7 message is
-- 160 characters and the alert already uses about a hundred; a 36-character uuid
-- pushes every single job into two segments, which is double the cost per job
-- forever. It also looks like spam. Eight characters keeps the whole link near
-- twenty and reads like something a person made.
--
-- Generated by the database rather than in application code so it cannot be
-- forgotten on an insert path — and there are two, since lead creation falls
-- back to essential-fields-only when a column is rejected.
--
-- base64 of 6 random bytes is exactly 8 characters; translate() maps the three
-- characters that are unsafe or ugly in a URL onto letters. 2^48 possibilities
-- with a unique index behind it: a collision is not a practical concern, and if
-- one ever happened the insert fails loudly rather than handing two businesses
-- the same link.

alter table public.lead
  add column if not exists code text not null
  default translate(encode(gen_random_bytes(6), 'base64'), '+/=', 'xyz');

create unique index if not exists lead_code_idx on public.lead(code);

comment on column public.lead.code is
  'Short public-facing id used in the job alert link (/j/<code>). Not a secret — the route still requires a session and RLS still scopes the row.';

-- ======================================================================
-- 20260809170000_gsm7_confirmation_default.sql
-- ======================================================================

-- Takes the em dash out of the confirmation text, because it triples the cost.
--
-- The default template opened "Thanks {{caller_name}} — we have logged". The em
-- dash does not exist in the GSM-7 alphabet, and one character outside GSM-7
-- forces the entire SMS into UCS-2 encoding, where a segment is 70 characters
-- rather than 160. Every confirmation FlowPilot has ever sent to a member of the
-- public has therefore been billed as two or three segments to carry one
-- sentence, and the same mistake was in the owner's job alert.
--
-- A hyphen is in GSM-7 and reads identically at a glance on a phone.
--
-- Existing businesses are migrated too, but only where they still have the old
-- default. Anyone who has written their own wording keeps it — correcting our
-- default is not licence to rewrite somebody's own words to their customers,
-- even to save them money.

alter table public.business_profile
  alter column confirmation_sms_template
  set default 'Thanks {{caller_name}} - we have logged: {{job_type}}, {{location}}. {{business_name}} will be in touch shortly.';

update public.business_profile
set confirmation_sms_template =
  'Thanks {{caller_name}} - we have logged: {{job_type}}, {{location}}. {{business_name}} will be in touch shortly.'
where confirmation_sms_template =
  'Thanks {{caller_name}} — we have logged: {{job_type}}, {{location}}. {{business_name}} will be in touch shortly.';

-- ======================================================================
-- 20260812120000_default_to_the_plan_we_sell.sql
-- ======================================================================

-- Stop stamping every new business with a plan nobody can buy.
--
-- `business.plan` defaulted to 'starter' and so did create_business_for_current_user,
-- from back when three tiers were sold. Only 'pro' is sold now, so every signup
-- was being written as Starter — and the product believed it:
--
--   * Billing showed "Starter — €49/month · up to 50 answered calls", which is
--     not a thing anybody can purchase.
--   * getUsage() metered them against Starter's 50 calls instead of 200, so the
--     dashboard would have warned a paying customer they were near a limit that
--     is not theirs.
--
-- Nobody has ever subscribed, so moving existing rows is safe. The update is
-- narrowed to businesses that never reached checkout anyway — a real Starter
-- subscriber, if one ever existed, keeps the tier they pay for.
--
-- The default still names a plan in SQL, which will drift again if what we sell
-- changes. The durable fix is in the application: signup now passes soldPlan()
-- explicitly, so this default is a fallback rather than the source of truth.

alter table public.business
  alter column plan set default 'pro';

update public.business
set plan = 'pro'
where plan = 'starter'
  and subscription_status in ('incomplete', 'trialing')
  and stripe_subscription_id is null;

create or replace function public.create_business_for_current_user(
  business_name text,
  selected_plan text default 'pro'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := (select auth.uid());
  new_business_id uuid;
  safe_plan text := coalesce(selected_plan, 'pro');
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if business_name is null or length(trim(business_name)) = 0 then
    raise exception 'Business name is required';
  end if;

  -- Still validated rather than trusted. A user can edit their own auth
  -- metadata, so the plan arriving here is an expression of intent and never
  -- proof of payment — entitlement comes from the Stripe webhook alone.
  if safe_plan not in ('starter', 'pro', 'business') then
    safe_plan := 'pro';
  end if;

  -- One business per user until team accounts exist (roadmap Phase 7). Returning
  -- the existing id rather than raising makes this safe to call on every page
  -- load, which is what lets onboarding work whether or not email confirmation
  -- is enabled on the project.
  select business_id into new_business_id
  from public.business_member
  where user_id = current_user_id
  limit 1;

  if new_business_id is not null then
    return new_business_id;
  end if;

  insert into public.business (name, plan)
  values (trim(business_name), safe_plan)
  returning id into new_business_id;

  insert into public.business_member (business_id, user_id, role)
  values (new_business_id, current_user_id, 'owner');

  return new_business_id;
end;
$$;

revoke all on function public.create_business_for_current_user(text, text) from public;
grant execute on function public.create_business_for_current_user(text, text) to authenticated;

-- ======================================================================
-- 20260812150000_blocked_callers.sql
-- ======================================================================

-- ---------------------------------------------------------------------------
-- Callers the receptionist should never answer
--
-- Two different people ask for this and they want the same mechanism. The
-- tradesman whose wife rings and hears "Hello, Byrne Plumbing, sorry we missed
-- your call" — that is the moment the product feels like it took something
-- over rather than helped. And the one getting six scam calls a week who does
-- not want a job record created for any of them.
--
-- Worth being precise about what this can do. By the time a call arrives here
-- it has already been missed: their phone rang, they did not pick up, and the
-- carrier forwarded it. So blocking cannot mean "put them through" — that has
-- already failed. It means we do not answer, and the call falls back to
-- whatever their carrier does with an unanswered forward.
--
-- Stored per business rather than globally. One person's spam is another's
-- supplier, and a shared blocklist would be us making that call for them.
-- ---------------------------------------------------------------------------

create table public.blocked_caller (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,

  -- E.164, normalised on the way in. Matching a number typed four different
  -- ways is the whole job here, so the normalising happens once at write time
  -- rather than on every inbound call.
  number text not null,

  -- "Sarah", "that scam crowd". Optional, and only ever shown to the owner —
  -- it exists so a list of bare numbers is still readable in six months.
  label text,

  /*
   * Proof it is working.
   *
   * Without this a blocklist is a promise with no evidence: somebody adds a
   * number and can never tell whether it did anything. A count and a date turn
   * it into "blocked 3 times, last Tuesday", which is also how they notice
   * they have blocked the wrong number.
   */
  blocked_count integer not null default 0,
  last_blocked_at timestamptz,

  created_at timestamptz not null default now(),

  -- The same number twice in one list is a no-op with a confusing UI. Adding
  -- an existing number updates the label instead of creating a duplicate.
  unique (business_id, number)
);

create index blocked_caller_business_id_idx
  on public.blocked_caller(business_id);

/*
 * The lookup every inbound call makes, before answering.
 *
 * Deliberately covering: the incoming route asks "is this exact number blocked
 * for this business", and this index answers it without touching the table.
 * It sits in front of the most latency-sensitive path in the product — a
 * caller is listening to silence while it runs.
 */
create index blocked_caller_lookup_idx
  on public.blocked_caller(business_id, number);

alter table public.blocked_caller enable row level security;

-- Owned entirely by the business, like notification rules. The server reads it
-- through the admin client during a call, which bypasses RLS by design.
create policy blocked_caller_all_own on public.blocked_caller
  for all using (public.is_business_member(business_id))
  with check (public.is_business_member(business_id));

-- ======================================================================
-- 20260813120000_appointments.sql
-- ======================================================================

-- ---------------------------------------------------------------------------
-- The tradesman's diary
--
-- Written and edited by the business, only ever read by the receptionist. That
-- boundary is the point of the feature, not a limitation of it: an AI that can
-- write to somebody's calendar can double-book them, and a plumber ringing a
-- customer to cancel a job a robot agreed to is the failure that ends the
-- account. There is no code path that lets the receptionist insert here.
--
-- Days and parts of days, not clock times. A tradesman says "Thursday morning",
-- not "Thursday 09:15", and a part-of-day is enough for both things this table
-- exists to do — telling a customer when to expect him, and telling the
-- receptionist which days are already heavy. Exact times can be added later if
-- anybody actually asks; guessing now would build a precision the trade does
-- not work in.
--
-- lead_id is nullable on purpose. Half a tradesman's week never came through a
-- phone call — a regular customer, a foreman, his brother-in-law — and a diary
-- that only knows about FlowPilot leads would give the receptionist a
-- confidently wrong picture of how busy he is.
-- ---------------------------------------------------------------------------

create table public.appointment (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.business(id) on delete cascade,

  /*
   * The job this came from, if it came from one.
   *
   * `on delete set null` rather than cascade: erasing a lead — which a caller
   * can request under GDPR — must not silently delete a job out of somebody's
   * diary. The appointment carries its own copy of the details it needs.
   */
  lead_id uuid references public.lead(id) on delete set null,

  scheduled_for date not null,
  slot text not null default 'anytime'
    check (slot in ('morning', 'afternoon', 'anytime')),

  /** What the job is, in his words. "Rewire kitchen". */
  title text not null,

  /*
   * Copied from the lead rather than joined to it, so the diary still reads
   * correctly after a lead is erased, and so a job added by hand can carry the
   * same details without inventing a lead to hang them off.
   */
  customer_name text,
  customer_number text,
  location text,
  notes text,

  /*
   * When the customer was told, and never set by the system on its own.
   *
   * The confirmation text goes out only when the owner taps send. It is a
   * message in his name to his customer, and one that fires unexpectedly is
   * how somebody stops trusting the whole feature.
   */
  customer_notified_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

/*
 * The two reads this table gets, and they are different shapes.
 *
 * The calendar page asks for one business's jobs from today forward. The
 * receptionist asks, mid-call with somebody on the line, which of the next
 * fortnight's days are already busy. Both are business_id then date, so one
 * index serves them.
 */
create index appointment_business_date_idx
  on public.appointment(business_id, scheduled_for);

alter table public.appointment enable row level security;

create policy appointment_all_own on public.appointment
  for all using (public.is_business_member(business_id))
  with check (public.is_business_member(business_id));

create trigger appointment_set_updated_at
  before update on public.appointment
  for each row execute function public.set_updated_at();

-- ======================================================================
-- 20260813140000_only_create_on_a_plan_we_sell.sql
-- ======================================================================

-- ---------------------------------------------------------------------------
-- A new business can only be created on a plan that is actually sold
--
-- The validation here already knew not to trust the caller — auth metadata is
-- user-editable, so the plan arriving is an expression of intent and never
-- proof of payment. What it got wrong was the list it validated against:
-- ('starter', 'pro', 'business'), written when all three were on sale.
--
-- Starter and Business were withdrawn. The check kept admitting them, so a
-- crafted signup could still create a business row on a tier the site does not
-- advertise, at an allowance nobody costed. The application-side fallback had
-- the matching half of the fault — it defaulted to the literal 'starter' — and
-- both are fixed together, because either one alone leaves the hole open.
--
-- This is the same defect that once billed customers against Starter's 50-call
-- allowance while they paid for Pro: a withdrawn tier left reachable because
-- removing it looked riskier than leaving it.
--
-- The business.plan CHECK constraint deliberately still permits all three.
-- Rows created before the tiers were withdrawn carry those values and must
-- continue to load — getPlan() falls back for exactly that reason. What
-- narrows is what can be created from now on, not what may exist.
-- ---------------------------------------------------------------------------

create or replace function public.create_business_for_current_user(
  business_name text,
  selected_plan text default 'pro'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := (select auth.uid());
  new_business_id uuid;
  safe_plan text := coalesce(selected_plan, 'pro');
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if business_name is null or length(trim(business_name)) = 0 then
    raise exception 'Business name is required';
  end if;

  /*
   * One plan is sold, so one plan can be created. Anything else — a withdrawn
   * tier, a typo, a crafted value — becomes the plan on sale rather than being
   * rejected: a signup must not fail over a field that only ever records
   * intent, and entitlement comes from the Stripe webhook regardless.
   *
   * When a second plan goes on sale this list is what has to change, and it
   * should be a deliberate edit rather than a value that was already permitted.
   */
  if safe_plan not in ('pro') then
    safe_plan := 'pro';
  end if;

  -- One business per user until team accounts exist (roadmap Phase 7). Returning
  -- the existing id rather than raising makes this safe to call on every page
  -- load, which is what lets onboarding work whether or not email confirmation
  -- is enabled on the project.
  select business_id into new_business_id
  from public.business_member
  where user_id = current_user_id
  limit 1;

  if new_business_id is not null then
    return new_business_id;
  end if;

  insert into public.business (name, plan)
  values (trim(business_name), safe_plan)
  returning id into new_business_id;

  insert into public.business_member (business_id, user_id, role)
  values (new_business_id, current_user_id, 'owner');

  return new_business_id;
end;
$$;

revoke all on function public.create_business_for_current_user(text, text) from public;
grant execute on function public.create_business_for_current_user(text, text) to authenticated;

-- ======================================================================
-- 20260814100000_pause_the_receptionist.sql
-- ======================================================================

-- ---------------------------------------------------------------------------
-- Turning the receptionist off for a while
--
-- A tradesperson on holiday, or having a week where he wants his own phone
-- back, needs a switch. Without one the only way to stop FlowPilot answering is
-- to dial ##002# and clear forwarding at the carrier — which also wipes the
-- network voicemail we told him to turn off during setup, and leaves him
-- re-dialling two codes to come back. That is not a setting, it is a
-- workaround.
--
-- A column rather than a new business.status value. `status` distinguishes
-- onboarding, active and suspended, and suspended means WE stopped the account
-- — a billing or abuse decision that the customer cannot undo. Overloading it
-- with a state the customer controls would make "why is this account not
-- answering" a question with two very different answers and one field.
--
-- Nullable timestamp rather than a boolean, because when it was paused is worth
-- knowing. A receptionist quietly off for three weeks is the most likely
-- explanation for "I'm not getting any jobs", and a date answers that
-- immediately where a boolean starts a conversation.
-- ---------------------------------------------------------------------------

alter table public.business
  add column receptionist_paused_at timestamptz;

comment on column public.business.receptionist_paused_at is
  'When the owner paused the receptionist. Null means it is answering. Distinct from status = suspended, which is our decision rather than theirs.';

-- ======================================================================
-- 20260814120000_let_the_owner_pause.sql
-- ======================================================================

-- ---------------------------------------------------------------------------
-- The owner may actually write the pause switch
--
-- 20260731120500 revoked UPDATE on public.business from authenticated and
-- granted it back one column at a time, so that a customer could not hand
-- themselves a free plan by writing `plan` or `subscription_status` directly.
-- That is the right shape, and it has a cost: every column added afterwards is
-- read-only to the owner until somebody remembers to grant it.
--
-- receptionist_paused_at was added in 20260814100000 and never granted. The
-- switch in Settings therefore failed for every customer with "permission
-- denied for column receptionist_paused_at" — the one control that answers
-- "is my phone being covered right now", rejected by the database.
--
-- Granted narrowly, to this column alone. It is the customer's decision by
-- definition: it is theirs to make, and it is distinct from status =
-- suspended, which is ours and stays service-role only.
-- ---------------------------------------------------------------------------

grant update (receptionist_paused_at) on public.business to authenticated;

-- ======================================================================
-- 20260814160000_say_who_is_texting.sql
-- ======================================================================

-- ---------------------------------------------------------------------------
-- Say whose receptionist is texting, before anything else
--
-- The confirmation goes to a stranger. Somebody rings a plumber, gets no
-- answer, and thirty seconds later an unfamiliar number is telling them their
-- own address. That reads as a scam unless the very first thing they see is the
-- name of the business they just rang — and the old wording opened "Thanks
-- {{caller_name}} - we have logged" and did not name the business until the
-- final clause, long after they had decided what it was.
--
-- It matters more than it should because Irish landline numbers cannot send SMS
-- at all. These go out from a US number and will keep doing so until a sender
-- ID is registered with ComReg, which needs a company registration the business
-- does not have yet. The wording cannot make the number Irish. It can make the
-- number make sense.
--
-- "No need to reply to this number" is literal, not manners: nothing handles
-- inbound SMS there, so a customer correcting a misheard address would be
-- typing into nowhere.
--
-- {{caller_name}} is dropped. It was frequently empty — callers ring off before
-- giving a name — and "Thanks  - we have logged" is a worse opening than none.
--
-- Every character stays inside GSM-7. One em dash would push the whole message
-- into UCS-2, where a segment is 70 characters rather than 160, doubling what
-- every confirmation costs to send.
-- ---------------------------------------------------------------------------

alter table public.business_profile
  alter column confirmation_sms_template
  set default '{{business_name}} automated receptionist. Your job is logged: {{job_type}}, {{location}}. You will get a call back - no need to reply to this number.';

-- Existing businesses that never customised theirs, moved across with it. A
-- business that wrote its own wording keeps it; only the untouched default is
-- replaced, matched exactly against both prior defaults.
update public.business_profile
set confirmation_sms_template =
  '{{business_name}} automated receptionist. Your job is logged: {{job_type}}, {{location}}. You will get a call back - no need to reply to this number.'
where confirmation_sms_template in (
  'Thanks {{caller_name}} - we have logged: {{job_type}}, {{location}}. {{business_name}} will be in touch shortly.',
  'Thanks {{caller_name}} — we have logged: {{job_type}}, {{location}}. {{business_name}} will be in touch shortly.'
);

