import WeekStrip, { weekFrom } from "@/components/WeekStrip";
import { previewAppointments } from "@/lib/app-preview";
import { appointmentText } from "@/lib/appointment-text";
import { availabilityPrompt } from "@/lib/availability";
import { DEMO_BUSINESS_NAME } from "@/lib/demo-example";
import { isoDateIn, startOfDayIn } from "@/lib/today";

/**
 * The week, and the two things having a diary actually buys you.
 *
 * The same WeekStrip the calendar page renders, so the site cannot show a
 * layout the product does not have. It replaced a month grid that measured 848
 * by 751 pixels here — taller than the phone beside it, and six dots scattered
 * across 43 mostly-empty cells said nothing about what a diary is for.
 *
 * Both panels underneath are generated by the functions the product runs:
 * appointmentText() is what actually texts a customer, and availabilityPrompt()
 * is what the receptionist is actually given. Neither can drift into promising
 * wording that does not exist — and the second one gates itself, so if the
 * receptionist ever stopped being told about busy days, the claim would
 * disappear from the site rather than become a lie.
 */
export default function DiaryPreview() {
  // Ireland's day, not the server's. Vercel runs UTC.
  const now = startOfDayIn();
  const appointments = previewAppointments(now);
  const week = weekFrom(appointments, now);

  const busiest = [...week].sort((a, b) => b.jobs.length - a.jobs.length)[0];
  const booked = busiest?.jobs[0];

  const customerText = booked
    ? appointmentText(
        { ...booked, customer_name: "John", slot: "morning" },
        DEMO_BUSINESS_NAME,
        null,
        now,
      )
    : null;

  // Quoted from the real prompt, so the claim below stays true: the
  // receptionist may say a day is busy and may never say one is free.
  const knowsAboutBusyDays = Boolean(availabilityPrompt(appointments, now));

  return (
    <div>
      <WeekStrip days={week} today={isoDateIn()} />

      <div className="mt-3 grid gap-3 sm:grid-cols-2">
        {customerText && (
          <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-4">
            <p className="text-[11px] uppercase tracking-[0.12em] text-zinc-400">
              Your customer gets
            </p>
            <div className="mt-2.5 rounded-2xl rounded-bl-sm bg-[#26262b] px-3.5 py-2.5">
              <p className="text-[12px] leading-[1.55] text-zinc-50">
                {customerText}
              </p>
            </div>
            <p className="mt-2.5 text-[12px] leading-5 text-zinc-500">
              Only when you tap send. Nothing goes out on its own.
            </p>
          </div>
        )}

        {knowsAboutBusyDays && (
          <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-4">
            <p className="text-[11px] uppercase tracking-[0.12em] text-zinc-400">
              The next caller hears
            </p>
            <p className="mt-2.5 text-[13px] leading-6 text-zinc-300">
              &ldquo;He&apos;s fairly booked{" "}
              {busiest ? busiest.weekday : "that day"}. I&apos;ll put you down
              and he&apos;ll ring you back — would another day suit?&rdquo;
            </p>
            <p className="mt-2.5 text-[12px] leading-5 text-zinc-500">
              It can say a day is busy. It can never promise a slot.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
