import LeadCard from "@/app/(app)/dashboard/LeadCard";
import PhoneFrame from "@/components/PhoneFrame";
import WeekStrip, { weekFrom } from "@/components/WeekStrip";
import { previewAppointments, previewLeads } from "@/lib/app-preview";
import { availabilityPrompt } from "@/lib/availability";
import { appointmentText } from "@/lib/appointment-text";
import { isoDate } from "@/lib/month-grid";

/**
 * The app itself, on the marketing page.
 *
 * Renders the REAL components — LeadCard straight out of the dashboard,
 * WeekStrip straight out of the calendar — against fixtures. Not screenshots,
 * and not a hand-built imitation. Both go stale silently, and this site has
 * published a stale imitation three times: the disclosure line, the default
 * greeting and the animated phone all showed a product FlowPilot had stopped
 * being.
 *
 * This showed a month grid first, and it was wrong twice over. It measured 848
 * by 751 pixels — taller than the phone beside it — and a scatter of six dots
 * across 43 mostly-empty cells conveyed nothing about what a diary is for. The
 * heading above it promises "a diary that answers for you", and the grid
 * demonstrated neither half of that.
 *
 * So the week shows the jobs, and the two panels underneath show the answering:
 * the text a customer gets, and the line the next caller hears. Both are
 * generated by the functions the product actually uses, so the site cannot
 * claim wording the receptionist does not use.
 */
export default function InsideTheApp() {
  const now = new Date();
  const leads = previewLeads(now);
  const appointments = previewAppointments(now);
  const week = weekFrom(appointments, now);

  /*
   * The busiest day, and the message about it — both derived rather than
   * written out. appointmentText is the function that texts real customers, and
   * availabilityPrompt is what the receptionist is actually given, so neither
   * panel can drift into promising something the product does not do.
   */
  const busiest = [...week].sort((a, b) => b.jobs.length - a.jobs.length)[0];
  const booked = busiest?.jobs[0];

  const customerText = booked
    ? appointmentText(
        { ...booked, customer_name: "Mary", slot: "morning" },
        "Byrne Electrical",
        null,
        now,
      )
    : null;

  // Quoted from the real prompt, so the claim below it stays true: the
  // receptionist may say a day is busy and may never say one is free.
  const knowsAboutBusyDays = Boolean(availabilityPrompt(appointments, now));

  return (
    <div className="grid items-start gap-10 lg:grid-cols-[auto_1fr] lg:gap-12">
      <div className="mx-auto w-full max-w-[248px]">
        <PhoneFrame className="h-[430px] w-[236px]">
          <div className="flex min-h-0 flex-1 flex-col px-2.5 pt-1">
            <p className="text-lg font-semibold tracking-tight">Jobs</p>
            <p className="mt-0.5 text-[11px] text-zinc-400">
              {leads.filter((lead) => lead.status !== "booked").length} waiting
              on you.
            </p>

            {/*
              `inert`, and not decoration. LeadCard is the real component, so it
              carries real links: a stretched link to /dashboard/<id> and a tel:
              on the caller's number. On a public page the first bounces a
              visitor to a login screen and the second would dial a plausible
              Irish mobile belonging to somebody who never asked to be in a
              demo.
            */}
            <div inert className="mt-3 origin-top scale-[0.82] space-y-2.5">
              {leads.slice(0, 2).map((lead) => (
                <LeadCard key={lead.id} lead={lead} />
              ))}
            </div>
          </div>
        </PhoneFrame>
        <p className="mt-4 text-center text-sm leading-6 text-zinc-400">
          Every call becomes a job, with the date they asked for. Tap the number
          to ring them back.
        </p>
      </div>

      <div>
        <WeekStrip days={week} today={isoDate(now)} />

        <div className="mt-3 grid gap-3 sm:grid-cols-2">
          {customerText && (
            <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-4">
              <p className="text-[10px] uppercase tracking-[0.12em] text-zinc-500">
                Your customer gets
              </p>
              <div className="mt-2.5 rounded-2xl rounded-bl-sm bg-[#26262b] px-3.5 py-2.5">
                <p className="text-[12px] leading-[1.55] text-zinc-50">
                  {customerText}
                </p>
              </div>
            </div>
          )}

          {knowsAboutBusyDays && (
            <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-4">
              <p className="text-[10px] uppercase tracking-[0.12em] text-zinc-500">
                The next caller hears
              </p>
              <p className="mt-2.5 text-[13px] leading-6 text-zinc-300">
                &ldquo;He&apos;s fairly booked{" "}
                {busiest ? busiest.weekday : "that day"}. I&apos;ll put you down
                and he&apos;ll ring you back — would another day suit?&rdquo;
              </p>
            </div>
          )}
        </div>

        <p className="mt-4 max-w-lg text-sm leading-6 text-zinc-400">
          Book a job from the call and your customer is told when you&apos;ll be
          there. Your receptionist can see which days are heavy — it never
          arranges anything itself.
        </p>
      </div>
    </div>
  );
}
