"use client";

import { useEffect, useRef, useState } from "react";
import {
  DEMO_BUSINESS_NAME,
  DEMO_GREETING,
  EXAMPLE_CAPTURED,
  EXAMPLE_TURNS,
} from "@/lib/demo-example";
import { composeOpening } from "@/lib/disclosure";

type Turn = { role: "assistant" | "caller"; text: string };

/*
 * Generated by the same function a live call uses, not retyped.
 *
 * This was a hardcoded string under a comment insisting it matched what
 * openingLine() produces. It did not: the disclosure had been rewritten and the
 * demo still opened "This is an automated assistant, and I'll take notes" —
 * words no caller had heard for months, on the page where a visitor decides
 * whether to trust us. A promise in a comment is not a mechanism.
 */
const GREETING = composeOpening(DEMO_BUSINESS_NAME, DEMO_GREETING);

/*
 * Planned work, which is what most callers are ringing about. These were three
 * emergencies, so every visitor who tried the demo was steered into
 * demonstrating a product we are not selling.
 */
/*
 * Short enough to sit on one line in a chip at 390px. The first of these ran to
 * fifty-three characters and wrapped into a ragged two-line pill that was wider
 * than it was useful.
 */
const OPENERS = [
  "We're redoing the kitchen",
  "I need a bathroom fitted",
  "My radiator won't heat up",
];

/**
 * Plausible next answers, offered once the receptionist has asked something.
 *
 * Suggestions rather than auto-play: the visitor still chooses every reply, so
 * the conversation stays genuinely theirs, but answering costs one click
 * instead of a sentence of typing. A demo that requires four paragraphs of
 * input from a browsing stranger is a demo most people abandon halfway.
 */
function suggestFor(question: string): string[] {
  const asked = question.toLowerCase();

  if (asked.includes("where") || asked.includes("address")) {
    return ["14 Griffith Avenue, Glasnevin", "Raheny, Dublin 5"];
  }
  // Was the owner's own name, which put it on the public homepage as a
  // suggestion chip. A demo caller should be nobody in particular.
  if (asked.includes("name")) return ["John", "John Murphy"];
  // Timing before urgency, and both offered as dates rather than a panic — the
  // receptionist now asks when they want it done before it asks how bad it is.
  if (asked.includes("when") || asked.includes("suit") || asked.includes("hoping")) {
    return ["Week of the 22nd", "Sometime next month, no rush"];
  }
  if (asked.includes("emergency") || asked.includes("urgent") || asked.includes("wait")) {
    return ["It can wait, it's planned work", "It's fairly urgent"];
  }
  if (asked.includes("water") || asked.includes("mains") || asked.includes("off")) {
    return ["Yes, I've turned it off", "No, I can't find the valve"];
  }
  return ["Yes", "No, that's everything"];
}

const FIELD_LABELS: Record<string, string> = {
  job_type: "Job",
  location: "Address",
  urgency: "Urgency",
  contact_name: "Name",
  preferred_time: "Wants it",
};

/*
 * Timing sits with the job, not last behind urgency.
 *
 * The order here is what a visitor watches assemble, so it is an argument about
 * what matters. Urgency led and the date trailed, which sold an emergency line;
 * for planned work the date is the second thing you want to know after what the
 * job is. Urgency stays at the end — real when it comes up, not the headline.
 */
const FIELD_ORDER = [
  "contact_name",
  "job_type",
  "location",
  "preferred_time",
  "urgency",
];

export default function LiveDemo() {
  const [turns, setTurns] = useState<Turn[]>([
    { role: "assistant", text: GREETING },
  ]);
  const [captured, setCaptured] = useState<Record<string, string>>({});
  const [draft, setDraft] = useState("");
  const [thinking, setThinking] = useState(false);
  const [complete, setComplete] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [unavailable, setUnavailable] = useState(false);

  const threadRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Keep the newest turn in view without yanking the whole page around.
    threadRef.current?.scrollTo({
      top: threadRef.current.scrollHeight,
      behavior: "smooth",
    });
  }, [turns, thinking]);

  const lastAssistant = [...turns].reverse().find((t) => t.role === "assistant");

  /*
   * "Started" means the receptionist has actually asked something, not merely
   * that the visitor has typed. If a turn failed, the only assistant line is
   * still the greeting — offering "Yes / No, that's everything" as replies to
   * "What's the problem?" would look broken on top of already having failed.
   */
  const answered = turns.filter((turn) => turn.role === "assistant").length > 1;
  const suggestions = answered
    ? suggestFor(lastAssistant?.text ?? "")
    : OPENERS;

  async function send(text: string) {
    const message = text.trim();
    if (!message || thinking || complete) return;

    const withCaller: Turn[] = [...turns, { role: "caller", text: message }];
    setTurns(withCaller);
    setDraft("");
    setThinking(true);
    setError(null);

    try {
      const response = await fetch("/api/demo", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ message, transcript: turns }),
      });

      const data = await response.json();

      if (!response.ok) {
        /*
         * Take the failed turn back out of the thread.
         *
         * Leaving it would send it again on the retry, so the receptionist
         * would receive "My boiler has burst" twice and answer the duplicate —
         * a second failure caused entirely by the first.
         */
        setTurns(turns);
        setDraft(message);

        /*
         * 503 means the receptionist itself is unreachable, not that this
         * particular message failed — retrying will fail the same way.
         *
         * Falling back to the worked example rather than leaving an error box
         * where the proof should be. Somebody who typed a message and got
         * nothing has been given less than if we had never invited them to
         * try, and this section carries most of the argument for the product.
         * Labelled as an example, because pretending it is live would be
         * exactly the dishonesty the live demo exists to avoid.
         */
        if (response.status === 503) {
          setUnavailable(true);
          return;
        }

        setError(data.error ?? "Something went wrong. Try again.");
        return;
      }

      setTurns([...withCaller, { role: "assistant", text: data.speech }]);
      setCaptured((current) => ({ ...current, ...(data.captured ?? {}) }));
      if (data.complete) setComplete(true);
    } catch {
      setError("Couldn't reach the receptionist. Try again in a moment.");
    } finally {
      setThinking(false);
    }
  }

  /*
   * What is on screen, which is the live conversation until the receptionist
   * becomes unreachable and the worked example takes over.
   */
  const shownTurns = unavailable ? EXAMPLE_TURNS : turns;
  const shownCaptured = unavailable ? EXAMPLE_CAPTURED : captured;
  const ended = unavailable || complete;

  const rows = FIELD_ORDER.filter((key) => shownCaptured[key]).map((key) => ({
    key,
    label: FIELD_LABELS[key],
    value: shownCaptured[key],
  }));

  /*
   * Every field, captured or not.
   *
   * The empty state used to be a padded box reading "Nothing captured yet",
   * which is a lot of screen spent saying nothing. Showing the fields greyed out
   * from the start does three jobs at once: it kills the dead space, it teaches
   * what the receptionist is going to ask before anybody types, and it turns the
   * demo into something you watch fill in rather than something you read.
   */
  const record = FIELD_ORDER.map((key) => ({
    key,
    label: FIELD_LABELS[key],
    value: shownCaptured[key] ?? null,
  }));

  return (
    /*
     * Ordered so the conversation and the box you type into are always touching.
     * On a phone the job record used to sit between them, which put the input
     * an entire panel away from the thing it was replying to.
     */
    <div className="mx-auto grid max-w-4xl gap-4 lg:grid-cols-[1.35fr_1fr] lg:items-start">
      <div className="rounded-2xl border border-white/12 bg-white/[0.02] lg:col-start-1 lg:row-start-1">
        <div className="flex items-center gap-2.5 border-b border-white/8 px-5 py-3.5">
          {!ended ? (
            <span aria-hidden="true" className="flex h-3.5 items-end gap-[2px]">
              {[0, 1, 2].map((bar) => (
                <span
                  key={bar}
                  className="fp-wave-bar w-[2px] rounded-full bg-emerald-400"
                  style={{ height: "100%", animationDelay: `${bar * 120}ms` }}
                />
              ))}
            </span>
          ) : (
            <span
              aria-hidden="true"
              className="h-1.5 w-1.5 rounded-full bg-zinc-600"
            />
          )}
          <span className="text-[13px] text-zinc-300">
            O&apos;Brien Plumbing
          </span>
          <span className="ml-auto text-[11px] uppercase tracking-[0.12em] text-zinc-500">
            {unavailable ? "Example" : complete ? "Ended" : "On a call"}
          </span>
        </div>

        {/*
          Bubbles, and no minimum height. It was a 340px box holding one line of
          greeting, so nine-tenths of what a visitor first saw was black. Now it
          grows with the conversation and only scrolls once there is enough to
          scroll — and the two sides are told apart by shape and side, the way a
          person reads a conversation, rather than by a label above each line.
        */}
        <div
          ref={threadRef}
          className="max-h-[22rem] space-y-3 overflow-y-auto px-5 py-5"
        >
          {shownTurns.map((turn, index) => {
            const fromFlowPilot = turn.role === "assistant";

            return (
              <div
                key={index}
                className={`fp-rise-in flex ${fromFlowPilot ? "justify-start" : "justify-end"}`}
              >
                <p
                  className={`max-w-[85%] rounded-2xl px-4 py-2.5 text-[14px] leading-6 ${
                    fromFlowPilot
                      ? "rounded-tl-md bg-white/[0.07] text-white"
                      : "rounded-tr-md bg-white text-black"
                  }`}
                >
                  {turn.text}
                </p>
              </div>
            );
          })}

          {thinking && (
            <div className="flex justify-start">
              <p className="flex items-center gap-1.5 rounded-2xl rounded-tl-md bg-white/[0.07] px-4 py-3">
                {[0, 1, 2].map((dot) => (
                  <span
                    key={dot}
                    aria-hidden="true"
                    className="fp-wave-bar h-1.5 w-1.5 rounded-full bg-zinc-400"
                    style={{ animationDelay: `${dot * 160}ms` }}
                  />
                ))}
                <span className="sr-only">FlowPilot is answering</span>
              </p>
            </div>
          )}
        </div>
      </div>

      <div className="rounded-2xl border border-white/12 bg-white/[0.02] p-5 lg:col-start-2 lg:row-span-2 lg:row-start-1">
        <div className="flex items-center justify-between gap-3">
          <p className="text-[11px] uppercase tracking-[0.14em] text-zinc-400">
            Job record
          </p>
          <p className="text-[11px] text-zinc-500">
            {rows.length} of {record.length}
          </p>
        </div>

        <ul className="mt-4 space-y-3">
          {record.map((row) => (
            <li key={row.key} className="flex items-start gap-2.5">
              <span
                aria-hidden="true"
                className={`mt-0.5 flex h-4 w-4 flex-none items-center justify-center rounded-full text-[9px] ${
                  row.value
                    ? "bg-emerald-400/15 text-emerald-300"
                    : "border border-white/10 text-transparent"
                }`}
              >
                ✓
              </span>
              <span className="min-w-0">
                <span className="block text-[10px] uppercase tracking-[0.1em] text-zinc-500">
                  {row.label}
                </span>
                <span
                  className={`block text-[13px] leading-5 ${
                    row.value ? "fp-rise-in text-white" : "text-zinc-600"
                  }`}
                >
                  {row.value ?? "—"}
                </span>
              </span>
            </li>
          ))}
        </ul>

        {ended && (
          <div className="mt-5 border-t border-white/8 pt-4">
            <p className="text-[13px] text-emerald-300">
              Sent to Dave&apos;s phone
            </p>
            <p className="mt-1 text-[11px] leading-5 text-zinc-500">
              He rings back knowing the job before he dials.
            </p>
          </div>
        )}
      </div>

      <div className="lg:col-start-1 lg:row-start-2">
        {error && (
          <p
            role="alert"
            className="mb-3 rounded-xl border border-amber-500/25 bg-amber-500/10 px-4 py-3 text-sm text-amber-100"
          >
            {error}
          </p>
        )}

        {unavailable ? (
          <div className="rounded-2xl border border-white/12 bg-white/[0.03] p-5 text-center">
            <p className="text-sm text-zinc-300">
              The live demo is having a moment, so that&apos;s a real call it
              handled earlier rather than one you just had.
            </p>
            <p className="mx-auto mt-2 max-w-md text-xs leading-5 text-zinc-500">
              Worth knowing what happens when the same thing goes wrong on a
              live call: it keeps the caller talking, takes their details, and
              flags the job for you. It never hangs up on them.
            </p>
            <a
              href="/signup"
              className="mt-4 inline-block rounded-full bg-white px-6 py-3 text-sm font-semibold text-black transition hover:bg-zinc-200"
            >
              Set this up for my business
            </a>
          </div>
        ) : !complete ? (
          <>
            <form
              onSubmit={(event) => {
                event.preventDefault();
                send(draft);
              }}
              className="flex gap-2"
            >
              <input
                value={draft}
                onChange={(event) => setDraft(event.target.value)}
                placeholder={answered ? "Say something else…" : "Tell it about a job…"}
                aria-label="What a caller might say"
                maxLength={300}
                className="min-h-12 flex-1 rounded-full border border-white/15 bg-white/[0.05] px-5 text-[15px] text-white placeholder:text-zinc-500 transition focus:border-white/40 focus:outline-none focus:ring-2 focus:ring-white/10"
              />
              {/*
                Dimming a white button to 40% leaves a grey slab that reads as
                broken rather than as waiting — which is exactly how it looked at
                rest, before anybody had typed anything. It now holds a visible
                outline until there is something to send.
              */}
              <button
                type="submit"
                disabled={thinking || !draft.trim()}
                className="min-h-12 flex-none rounded-full bg-white px-6 text-[15px] font-semibold text-black transition hover:bg-zinc-200 disabled:bg-transparent disabled:text-zinc-500 disabled:ring-1 disabled:ring-inset disabled:ring-white/15"
              >
                Send
              </button>
            </form>

            <div className="mt-3">
              <p className="text-[11px] uppercase tracking-[0.12em] text-zinc-500">
                Or tap one
              </p>
              <div className="mt-2.5 flex flex-wrap gap-2">
                {suggestions.map((suggestion) => (
                  <button
                    key={suggestion}
                    type="button"
                    onClick={() => send(suggestion)}
                    disabled={thinking}
                    // 44px tall on phones, where these are the main way the demo
                    // gets driven; back to compact once there is a mouse.
                    className="flex min-h-11 items-center rounded-full border border-white/15 px-4 text-[13px] text-zinc-300 transition hover:border-white/30 hover:bg-white/5 hover:text-white disabled:opacity-40 sm:min-h-0 sm:py-2"
                  >
                    {suggestion}
                  </button>
                ))}
              </div>
            </div>
          </>
        ) : (
          <div className="rounded-2xl border border-white/12 bg-white/[0.03] p-5 text-center">
            <p className="text-sm text-zinc-300">
              That&apos;s a job captured, start to finish — without you touching
              your phone.
            </p>
            <a
              href="/signup"
              className="mt-4 inline-block rounded-full bg-white px-6 py-3 text-sm font-semibold text-black transition hover:bg-zinc-200"
            >
              Set this up for my business
            </a>
          </div>
        )}
      </div>
    </div>
  );
}
