-- A short code per lead, so the job alert can carry a link somebody can tap.
--
-- The alert text told a tradesperson a job existed and then left them to find
-- it: no way to act on it, and no route from the text to the job. Keeping track
-- meant remembering, unprompted, to open a website, while the text scrolled away
-- under WhatsApp. The text is the alert, the dashboard is the list of what you
-- still owe people, and this is what joins them.
--
-- Short rather than the uuid because this rides in an SMS. A GSM-7 message is
-- 160 characters and the alert already uses about a hundred; a 36-character uuid
-- pushes every single job into two segments, which is double the cost per job
-- forever. It also looks like spam. Eight characters keeps the whole link near
-- twenty and reads like something a person made.
--
-- Generated by the database rather than in application code so it cannot be
-- forgotten on an insert path — and there are two, since lead creation falls
-- back to essential-fields-only when a column is rejected.
--
-- base64 of 6 random bytes is exactly 8 characters; translate() maps the three
-- characters that are unsafe or ugly in a URL onto letters. 2^48 possibilities
-- with a unique index behind it: a collision is not a practical concern, and if
-- one ever happened the insert fails loudly rather than handing two businesses
-- the same link.

alter table public.lead
  add column code text not null
  default translate(encode(gen_random_bytes(6), 'base64'), '+/=', 'xyz');

create unique index lead_code_idx on public.lead(code);

comment on column public.lead.code is
  'Short public-facing id used in the job alert link (/j/<code>). Not a secret — the route still requires a session and RLS still scopes the row.';
